#### importando libreria numpy

In [285]:
import numpy as np 

### creando una lista de 10 elemnetos 

In [286]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#### trasformando la lista en una array

In [287]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### comprobando el tipo de objeto

In [288]:
type(arreglo)

numpy.ndarray

### corroborando el tipo de dato que tiene la estructura

In [289]:
arreglo.dtype

dtype('int32')

#### definiendo el array de int32 a float32

In [290]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

#### trasformando el tipo de dato

In [291]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

<h3 style = "color:blue "> <b>algunas funciones de numpy</b></h3>
<h4 style= "color: orange" > <b>

### obteniendo el promedio del array

In [292]:
promedio= np.mean(arreglo)
promedio

5.5

### obteniendo la mediana

In [293]:
mediana= np.median(arreglo)
mediana

5.5

## direcion estandar del arreglo 

In [294]:
desviacion= np.std(arreglo)
desviacion
#estadistica, obtiene la dispercion de los numeros respecto a su media

2.8722813232690143

### arreglo de 2 en 2 utilizando arange 

In [295]:
arreglonuevo2= np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

### generacion de arreglos solos unos

In [296]:
arreglo_de_uno= np.ones(20)
arreglo_de_uno

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

trasformado de flotantes a enteros 

In [297]:
#el tpo de numeros va a ser entero 
arreglo_int_unos= arreglo_de_uno.astype(int)
arreglo_int_unos

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### arreglos de ceros

In [298]:
arreglo_de_ceros= np.zeros(5)
arreglo_de_ceros

array([0., 0., 0., 0., 0.])

##### random

In [299]:
arreglo_aleatortio= np.random.rand(5)
arreglo_aleatortio
#aleatorios de 0 a uno

array([0.11074947, 0.92172496, 0.82635058, 0.37424789, 0.97211315])

#### arreglo aleatorio de 10 num enteros del 1 al 5

In [300]:
num_ale_ent= np.random.randint(1,5,10)
num_ale_ent

array([4, 2, 3, 4, 2, 4, 3, 3, 3, 1])

#### matriz aleatorioa

In [301]:
#matrixz alearoria de tres x tres, tres filas, tres columnas 
#anidacion de listas o arreglos
matriz= np.random.rand(3,3)
matriz 

array([[0.2646803 , 0.65489057, 0.1827065 ],
       [0.57300488, 0.32126719, 0.77561937],
       [0.50230521, 0.0165085 , 0.49986864]])

### matriz aleatoria de 3 num enterros del 1 al 100

In [302]:
matriz_2= np.random.randint(1,101,(10,10)) #10 por 10 filas columnas
matriz_2

array([[ 36,  76,  35,   4,  54,  34,  37,  10,  25,   7],
       [ 32,  11,  12,   1,  54,  25,  47,   5,  29,  34],
       [ 97,  85,  58,  85,  91,  74,  20,  79,  69,  81],
       [ 58,  55,  99,  51,  15,  53,  10,  96,  81,  67],
       [ 43,  83,  99,  11,  65,  31,   9,  59,  76,  39],
       [ 81,  44,   9,  50,  84,  35,  52,  19,  83,  21],
       [ 20,  12,  92,  54,  78,  60,  56,  81,  40,  14],
       [100,  45,  89,  15,  95,  49,  48,  95,  44,  90],
       [ 47,  12,  36,  50,  69,  71,  10,  71,  91,  53],
       [ 96,  42,  12,  29,  39,  51,  98,  45,  88,  35]])